# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

default_install_hook_types:
  - commit-msg # For conventional commit linting
  - post-checkout # For uv sync
  - post-merge # For uv sync
  - post-rewrite # For uv sync
  - pre-commit
  - prepare-commit-msg # For conventional commit linting
default_language_version:
  python: 3.12.9 # Keep in synch with /.pyproject.toml!
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 3e8a8703264a2f4a69428a0aa4dcb512790b2c8c  # frozen: v6.0.0
    hooks:
      - id: check-case-conflict
      - id: check-illegal-windows-names
      - id: check-json
      - id: check-symlinks
      - id: check-toml
      - id: check-vcs-permalinks
      - id: check-yaml
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: mixed-line-ending
      - id: pretty-format-json
        exclude: "^\\.release-please-manifest\\.json$" # Exclude auto-generated release-please manifest
        args:
          - --autofix
      - id: trailing-whitespace

  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 04f6651481db5a9efe774349a1bf6db4cb4c5a05  # frozen: 0.9.17
    hooks:
      - id: uv-lock # Check lock files
      - id: uv-sync # Sync. local .venv

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: d96cc7adddf7d15b77f99dbd5d20e037dfd1b29c  # frozen: v0.14.9
    hooks:
      - id: ruff-check # Run the linter & fix fixable issues
        args:
          - --fix
      - id: ruff-format

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: c2738302f5cf2bfb559c1f210950badb133613ea  # frozen: v1.19.0
    hooks:
      - id: mypy
        additional_dependencies:
          - numpy==1.26.4 # Yocto-defined; for numpy typing plugin
          - types-PyYAML # for YAML typing
        exclude: "(docs|site|.+/tests)/.+\\.py" # Exclude file where mypy is not needed; done here as it would otherwise fail on file discovery due to duplicated tests folders in the monorepo
        args:
          - --config-file=pyproject.toml # Use pyproject.toml for configuration

  - repo: https://github.com/hukkin/mdformat # Format markdown files
    rev: 82912cdaea4fb830f751504486a7879c70526547  # frozen: 1.0.0
    hooks:
      - id: mdformat
        additional_dependencies:
          - mdformat-beautysh # Use beautysh to format shell code blocks
          - mdformat-config # Format JSON, TOML & YAML code blocks
          - mdformat-footnote # Format footnotes
          - mdformat-front-matters # Format front matters
          - mdformat-gfm # Github Flavored Markdown
          - mdformat-ruff # Use ruff to lint code blocks
        exclude: "CHANGELOG\\.md$" # Exclude auto-generated files
        args:
          - --number
          - --wrap=120
          - --end-of-line=keep
          - --strict-front-matter # mdformat-front-matters: Enforce valid front-matter

  - repo: https://github.com/espressif/conventional-precommit-linter
    rev: aeba78b29b06233289a1a6ed80371a337e893e19  # frozen: v1.11.0
    hooks:
      - id: conventional-precommit-linter
        stages:
          - commit-msg
        # Keep configuration in sync with .validate-pr-title.yaml
        args:
          - --allow-breaking
          - --scopes=bash,git,github,python,themes,vs_code,windows_terminal
          - --types=build,chore,ci,docs,feat,fix,refactor,revert,test

  - repo: https://github.com/tweag/FawltyDeps # Check for unused dependencies
    rev: eeb37db10367fc47bfe80cf57087b86bc8d6d13e  # frozen: v0.20.0
    hooks:
      - id: check-undeclared
      - id: check-unused

  - repo: https://github.com/koalaman/shellcheck-precommit
    rev: 99470f5e12208ff0fb17ab81c3c494f7620a1d8d  # frozen: v0.11.0
    hooks:
      - id: shellcheck
        args:
          - --exclude=SC1017 # Carriage return is handled by git & pre-commit

  - repo: https://github.com/scop/pre-commit-shfmt
    rev: 2a30809d16bc7a60d9b97353c797f42b510d3368  # frozen: v3.12.0-2
    hooks:
      - id: shfmt
